### ISSUE TITLE
initial condition

### ISSUE THREAD

**Issue by zhh710** [myying/QG_Multiscale_DA#2]
Could you provide initial condition data? Or, how do I generate the initial conditions myself? What do I need to pay attention to? 
Thank you.

**Comment by myying** [comment]
You can use the generate_initial_condition.py script to create a random noise for initializing the QG model. Use the following syntax: 
    ./generate_initial_condition.py kmax nz amplitude power_law

kmax = n/2 - 1 is the maximum horizontal wavenumber, for n by n grid.
nz is the number of vertical levels
amplitude is the standard deviation of the noise
power_law controls the noise spectrum, power_law = 1 is a white noise, power_law < 1 is red noise (more noise variance in large scales)

Hope this helps.

**Comment by zhh710** [comment]
Thank you
